# -*- coding: utf-8 -*-
"""Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z_8abgf31Uf5f9vitOxhFAfiSNtNihSV
"""


import streamlit as st
from google import genai
import os

# Set API key
os.environ["GOOGLE_API_KEY"] = "AIzaSyAs19tt0iF7iDZsJv_hij8CH7Ow-76K-OY"

# Initialize Gemini client
client = genai.Client(api_key=os.environ["GOOGLE_API_KEY"])

MODEL = "models/gemini-2.5-flash"


# Function for sentiment analysis
def analyze_sentiment(text):

    prompt = f"""
    Analyze the sentiment of the following text.

    Return:
    - Sentiment (Positive, Negative, Neutral)
    - Short explanation

    Text: {text}
    """

    response = client.models.generate_content(
        model=MODEL,
        contents=prompt
    )

    return response.text


# Streamlit UI
st.title("LLM Sentiment Analysis")

user_input = st.text_area("Enter text")

if st.button("Analyze"):

    if user_input:
        result = analyze_sentiment(user_input)
        st.write(result)

    else:
        st.warning("Please enter some text")