# -*- coding: utf-8 -*-
"""Sentiment Analysis app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z_8abgf31Uf5f9vitOxhFAfiSNtNihSV
"""

pip install streamlit langchain langchain-google-genai python-dotenv

import streamlit as st
import os

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_google_genai import ChatGoogleGenerativeAI

# =========================
# API KEY
# =========================

os.environ["GOOGLE_API_KEY"] = "AIzaSyAs19tt0iF7iDZsJv_hij8CH7Ow-76K-OY"

# =========================
# LLM MODEL
# =========================

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0
)

# =========================
# PROMPT TEMPLATE
# =========================

prompt = ChatPromptTemplate.from_template(
"""
Analyze the sentiment of the following text.

Text: {text}

Respond with only one word:
Positive, Negative, or Neutral
"""
)

# =========================
# OUTPUT PARSER
# =========================

parser = StrOutputParser()

# =========================
# LLM CHAIN
# =========================

chain = prompt | llm | parser

# =========================
# STREAMLIT UI
# =========================

st.title("LLM Sentiment Analysis")

user_input = st.text_area("Enter text")

if st.button("Analyze Sentiment"):

    if user_input:

        result = chain.invoke({"text": user_input})

        st.subheader("Sentiment")
        st.write(result)

    else:
        st.warning("Please enter some text.")